### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by thorulf4** [bonsall2004/thread-master#1]
It was cool to read through your code, I definitely learnt something new :D

https://github.com/bonsall2004/thread-master/blob/3f4bf553745387aeb2c5e85d0e07876ec1a382de/includes/Task.hpp#L19-L24
While this pattern is perfectly fine, it does risk unnecessary copies if used with pass by value callbacks. From my count it would perform 3 copies where 1 would've been enough. If you decide to look into this I recommend taking a look at "perfect forwarding"

https://github.com/bonsall2004/thread-master/blob/07274b61ce1000b8f7b054d0c1cd6a2074f9ec97/examples/test.cpp#L19-L27
From an API design perspective being handed a raw pointer, you're in charge of deallocating is a bit much. Moving ownership to the dispatcher and making a more concise interface would be a nice to have.

Although based on your example, it would super cool if SetPeriodicTimer returned a function pointer as it would allow people to rewrite your example like this:
```c++
auto disableCallback = event.SetPeriodicTimer(std::chrono::milliseconds(100));
event2.SetTimer(7, disableCallback);
```

https://github.com/bonsall2004/thread-master/blob/07274b61ce1000b8f7b054d0c1cd6a2074f9ec97/includes/Dispatcher.hpp#L80
You rely a lot on new and delete, while it looks like you've done it correctly. I would push you a bit to think about ownership and consider using smart pointers where possible. I'm not entirely convinced THandle needs to be heap allocated, as its only 16 bytes (including padding)

**Comment by bonsall2004** [comment]
Thank you for your suggestion, added all of the above
